autodetect: true
createTime: '2025-11-24T06:07:28.302778534Z'
github:
  name: Documentation-for-TBS
  owner: tbsdigitallabs
  push:
    branch: ^master$
id: c586bbf4-5f87-4daa-8a6b-cd4353e7f120
name: autorun
resourceName: projects/learninglab-478822/locations/global/triggers/c586bbf4-5f87-4daa-8a6b-cd4353e7f120
serviceAccount: projects/learninglab-478822/serviceAccounts/learninglab-run@learninglab-478822.iam.gserviceaccount.com
